services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: always
    ports:
      - "5680:5678"
    environment:
      - N8N_HOST=0.0.0.0 
      - N8N_PORT=5678
      
      - N8N_EDITOR_BASE_URL=http://192.168.1.17:5680/
      
      - GENERIC_TIMEZONE=Africa/Cairo
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
      - DB_TYPE=sqlite
      - DB_SQLITE_VACUUM_ON_STARTUP=true
    volumes:
      - ./n8n-data:/home/node/.n8n